In [8]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [9]:
data = pd.read_excel('Fig3-1.xls', header = None)

In [10]:
data

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,"U.S. Home Price and Related data, for Figure 3...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,See the book for description of data.,NaN,NaN,NaN,"Update Nominal Home Price Index, Click Additio...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Monthly data from January 1953 for prices, all...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nominal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Real,NaN,Real,NaN,NaN,NaN,NaN,Home,NaN,NaN,Nominal,NaN,NaN,Consumer,NaN,NaN,NaN,NaN
4,NaN,Home,NaN,Building,U.S.,NaN,NaN,NaN,Price,HPI,NaN,Building,NaN,NaN,Price,CPI Annual&,NaN,NaN,NaN
5,NaN,Price,NaN,Cost,Population,NaN,Long Rate,NaN,Index,Source,NaN,Cost,Build Cost,NaN,Index,Quarterly,NaN,NaN,CPI
6,Date,Index,Date,Index,Millions,Long Rate,Source,Date,From fig2.1Revised2011.xls,NaN,Date,Index,Source,Date,NaN,NaN,NaN,Date,Annual
7,1890,100,1890,51.3623,63.056,3.42,Homer,1890,3.5573,Grebler,1890,NaN,Grebler,1890,7.61165,Warren&Pearson,NaN,1890,7.61165
8,1891,88.0118,1891,47.2662,64.361,3.62,Homer,1891,3.20911,Grebler,1891,NaN,Grebler,1891,7.80194,Warren&Pearson,NaN,1891,7.80194
9,1892,95.4217,1892,52.0482,65.666,3.6,Homer,1892,3.26714,Grebler,1892,NaN,Grebler,1892,7.32621,Warren&Pearson,NaN,1892,7.32621
10,1893,92.2974,1893,44.6733,66.97,3.75,Homer,1893,3.40642,Grebler,1893,NaN,Grebler,1893,7.89709,Warren&Pearson,NaN,1893,7.89709
11,1894,123.98,1894,57.2634,68.275,3.7,Homer,1894,3.96932,Grebler,1894,NaN,Grebler,1894,6.85048,Warren&Pearson,NaN,1894,6.85048
12,1895,117.455,1895,61.4703,69.58,3.46,Homer,1895,3.60372,Grebler,1895,NaN,Grebler,1895,6.56505,Warren&Pearson,NaN,1895,6.56505
13,1896,100.303,1896,60.0689,70.885,3.6,Homer,1896,3.12206,Grebler,1896,NaN,Grebler,1896,6.66019,Warren&Pearson,NaN,1896,6.66019
14,1897,106.516,1897,62.3849,72.189,3.4,Homer,1897,3.22072,Grebler,1897,NaN,Grebler,1897,6.4699,Warren&Pearson,NaN,1897,6.4699
15,1898,110.184,1898,61.438,73.494,3.35,Homer,1898,3.42963,Grebler,1898,NaN,Grebler,1898,6.66019,Warren&Pearson,NaN,1898,6.66019
16,1899,103.853,1899,64.0446,74.799,3.1,Homer,1899,3.27875,Grebler,1899,NaN,Grebler,1899,6.75534,Warren&Pearson,NaN,1899,6.75534
17,1900,101.574,1900,49.4206,76.094,3.15,Homer,1900,3.7488,Grebler,1900,NaN,Grebler,1900,7.89709,Warren&Pearson,NaN,1900,7.89709
18,1901,87.3261,1901,51.2523,77.584,3.1,Homer,1901,3.14528,Grebler,1901,NaN,Grebler,1901,7.70679,Warren&Pearson,NaN,1901,7.70679
19,1902,100.474,1902,50.5162,79.163,3.18,Homer,1902,3.70818,Grebler,1902,NaN,Grebler,1902,7.89709,Warren&Pearson,NaN,1902,7.89709
20,1903,93.0749,1903,43.5435,80.632,3.3,Homer,1903,3.76621,Grebler,1903,NaN,Grebler,1903,8.65826,Warren&Pearson,NaN,1903,8.65826
21,1904,101.854,1904,47.0856,82.166,3.4,Homer,1904,3.9403,Grebler,1904,NaN,Grebler,1904,8.27768,Warren&Pearson,NaN,1904,8.27768
22,1905,87.2485,1905,47.111,83.822,3.48,Homer,1905,3.45284,Grebler,1905,NaN,Grebler,1905,8.46793,Warren&Pearson,NaN,1905,8.46793
23,1906,103.525,1906,51.7691,85.45,3.43,Homer,1906,4.09698,Grebler,1906,NaN,Grebler,1906,8.46793,Warren&Pearson,NaN,1906,8.46793
24,1907,109.317,1907,49.5447,87.008,3.67,Homer,1907,4.52061,Grebler,1907,NaN,Grebler,1907,8.84851,Warren&Pearson,NaN,1907,8.84851
25,1908,100.819,1908,50.1257,88.71,3.87,Homer,1908,4.07957,Grebler,1908,NaN,Grebler,1908,8.65826,Warren&Pearson,NaN,1908,8.65826
26,1909,95.3804,1909,44.0717,90.49,3.76,Homer,1909,3.98673,Grebler,1909,NaN,Grebler,1909,8.94367,Warren&Pearson,NaN,1909,8.94367
27,1910,93.1106,1910,37.9818,92.407,3.91,Homer,1910,4.3059,Grebler,1910,NaN,Grebler,1910,9.89517,Warren&Pearson,NaN,1910,9.89517
28,1911,97.5433,1911,42.2976,93.863,3.98,Homer,1911,4.20724,Grebler,1911,NaN,Grebler,1911,9.22909,Warren&Pearson,NaN,1911,9.22909
29,1912,102.365,1912,42.2541,95.335,4.01,Homer,1912,4.36973,Grebler,1912,NaN,Grebler,1912,9.134,Warren&Pearson,NaN,1912,9.134
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
834,2016.71,163.128,NaN,NaN,NaN,NaN,NaN,2016.71,184.059,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2016.71,241.428,BLS,NaN,NaN,NaN
835,2016.79,162.997,NaN,NaN,NaN,NaN,NaN,2016.79,184.141,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2016.79,241.729,BLS,NaN,NaN,NaN
836,2016.87,163.448,NaN,NaN,NaN,NaN,NaN,2016.87,184.363,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2016.87,241.353,BLS,NaN,NaN,NaN
837,2016.96,163.552,NaN,NaN,NaN,NaN,NaN,2016.96,184.541,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2016.96,241.432,BLS,NaN,NaN,NaN
838,2017.04,162.829,NaN,NaN,NaN,NaN,NaN,2017.04,184.795,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.04,242.839,BLS,NaN,NaN,NaN
839,2017.12,162.649,NaN,NaN,NaN,NaN,NaN,2017.12,185.172,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.12,243.603,BLS,NaN,NaN,NaN
840,2017.21,163.837,NaN,NaN,NaN,NaN,NaN,2017.21,186.676,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.21,243.801,BLS,NaN,NaN,NaN
841,2017.29,165.109,NaN,NaN,NaN,NaN,NaN,2017.29,188.683,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.29,244.524,BLS,NaN,NaN,NaN
842,2017.37,166.718,NaN,NaN,NaN,NaN,NaN,2017.37,190.685,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.37,244.733,BLS,NaN,NaN,NaN
843,2017.46,168.09,NaN,NaN,NaN,NaN,NaN,2017.46,192.428,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.46,244.955,BLS,NaN,NaN,NaN
844,2017.54,169.309,NaN,NaN,NaN,NaN,NaN,2017.54,193.69,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.54,244.786,BLS,NaN,NaN,NaN
845,2017.62,169.542,NaN,NaN,NaN,NaN,NaN,2017.62,194.538,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.62,245.519,BLS,NaN,NaN,NaN
846,2017.71,169.063,NaN,NaN,NaN,NaN,NaN,2017.71,195.015,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.71,246.819,BLS,NaN,NaN,NaN
847,2017.79,169.401,NaN,NaN,NaN,NaN,NaN,2017.79,195.282,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.79,246.663,BLS,NaN,NaN,NaN
848,2017.87,169.714,NaN,NaN,NaN,NaN,NaN,2017.87,195.647,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.87,246.669,BLS,NaN,NaN,NaN
849,2017.96,170.17,NaN,NaN,NaN,NaN,NaN,2017.96,196.058,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.96,246.524,BLS,NaN,NaN,NaN
850,2018.04,169.496,NaN,NaN,NaN,NaN,NaN,2018.04,196.345,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.04,247.867,BLS,NaN,NaN,NaN
851,2018.12,169.425,NaN,NaN,NaN,NaN,NaN,2018.12,197.152,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.12,248.991,BLS,NaN,NaN,NaN
852,2018.21,170.486,NaN,NaN,NaN,NaN,NaN,2018.21,198.836,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.21,249.554,BLS,NaN,NaN,NaN
853,2018.29,171.564,NaN,NaN,NaN,NaN,NaN,2018.29,200.888,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.29,250.546,BLS,NaN,NaN,NaN
854,2018.37,172.432,NaN,NaN,NaN,NaN,NaN,2018.37,202.745,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.37,251.588,BLS,NaN,NaN,NaN
855,2018.46,173.518,NaN,NaN,NaN,NaN,NaN,2018.46,204.347,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.46,251.989,BLS,NaN,NaN,NaN
856,2018.54,174.292,NaN,NaN,NaN,NaN,NaN,2018.54,205.272,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.54,252.006,BLS,NaN,NaN,NaN
857,2018.62,174.514,NaN,NaN,NaN,NaN,NaN,2018.62,205.647,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.62,252.146,BLS,NaN,NaN,NaN
858,2018.71,174.362,NaN,NaN,NaN,NaN,NaN,2018.71,205.707,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.71,252.439,BLS,NaN,NaN,NaN
859,2018.79,174.056,NaN,NaN,NaN,NaN,NaN,2018.79,205.709,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.79,252.885,BLS,NaN,NaN,NaN
860,2018.87,174.439,NaN,NaN,NaN,NaN,NaN,2018.87,205.471,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.87,252.038,BLS,NaN,NaN,NaN
861,2018.96,174.659,NaN,NaN,NaN,NaN,NaN,2018.96,205.073,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.96,251.233,BLS,NaN,NaN,NaN
862,2019.04,174.016,NaN,NaN,NaN,NaN,NaN,2019.04,204.708,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2019.04,251.712,BLS,NaN,NaN,NaN
863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019.12,252.776,BLS,NaN,NaN,NaN

При загрузке потерялось форматирование (жирные символы): Pandas не умеет работать с данными, содержащими форматирование. Но при сохранении файла после обработки мы сможем добавить форматирование. Если pandas отображает не все столбцы при выводе данных, вы можете воспользоваться следующим методом, чтобы выводить все столбцы:

In [6]:
#Added to the begining of this notebook
# pd.set_option('display.max_columns', None)

Основные параметры при чтении
Параметры, которые можно передавать методу pandas.read_excel():

1. io — первый параметр, в который мы передаём адрес файла, который хотим прочитать. Кроме адреса на диске, можно передавать адрес в интернете или специальный объект ExcelFile, о котором мы поговорим позже.
2. sheet_name — ссылка на лист в Excel-файле. Возможные варианты значения данного параметра:
    - 0 — значение по умолчанию, означает, что загружаем первую страницу (первый лист);
    - 'Sheet1' — можно передать название листа; обычно страницы называются 'SheetX', где X — номер листа, но могут использоваться и другие названия; 
    - [0, 1, 'Sheet3'] — список, содержащий номера или названия листов; в таком случае Pandas вернёт словарь, в котором ключами будут номера или названия листов, а значениями — их содержимое в виде DataFrame;
    - None — если передать такое значение, то Pandas прочитает все листы и вернёт их в виде словаря, как в предыдущем пункте.
3. na_values — список значений, которые будут считаться пропусками. Здесь всё точно так же, как при чтении .csv файла: ‘’, ‘#N/A’, ‘#N/A N/A’, ‘#NA’, ‘-1.#IND’, ‘-1.#QNAN’, ‘-NaN’, ‘-nan’, ‘1.#IND’, ‘1.#QNAN’, ‘N/A’, ‘NA’, ‘NULL’, ‘NaN’, ‘n/a’, ‘nan’, ‘null’

In [11]:
len(data)

864

Еще один способ прочитать Excel-файл — использовать pd.ExcelFile. Это специальный объект, которому на вход можно передать путь к файлу. Сначала мы создаем объект ExcelFile и передаём ему путь к файлу, после этого можем работать с файлом, считывая содержимое.

In [12]:
data_file = pd.ExcelFile('Fig3-1.xls')
data = pd.read_excel(data_file, header = None)
data

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,"U.S. Home Price and Related data, for Figure 3...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,See the book for description of data.,NaN,NaN,NaN,"Update Nominal Home Price Index, Click Additio...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Monthly data from January 1953 for prices, all...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nominal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Real,NaN,Real,NaN,NaN,NaN,NaN,Home,NaN,NaN,Nominal,NaN,NaN,Consumer,NaN,NaN,NaN,NaN
4,NaN,Home,NaN,Building,U.S.,NaN,NaN,NaN,Price,HPI,NaN,Building,NaN,NaN,Price,CPI Annual&,NaN,NaN,NaN
5,NaN,Price,NaN,Cost,Population,NaN,Long Rate,NaN,Index,Source,NaN,Cost,Build Cost,NaN,Index,Quarterly,NaN,NaN,CPI
6,Date,Index,Date,Index,Millions,Long Rate,Source,Date,From fig2.1Revised2011.xls,NaN,Date,Index,Source,Date,NaN,NaN,NaN,Date,Annual
7,1890,100,1890,51.3623,63.056,3.42,Homer,1890,3.5573,Grebler,1890,NaN,Grebler,1890,7.61165,Warren&Pearson,NaN,1890,7.61165
8,1891,88.0118,1891,47.2662,64.361,3.62,Homer,1891,3.20911,Grebler,1891,NaN,Grebler,1891,7.80194,Warren&Pearson,NaN,1891,7.80194
9,1892,95.4217,1892,52.0482,65.666,3.6,Homer,1892,3.26714,Grebler,1892,NaN,Grebler,1892,7.32621,Warren&Pearson,NaN,1892,7.32621
10,1893,92.2974,1893,44.6733,66.97,3.75,Homer,1893,3.40642,Grebler,1893,NaN,Grebler,1893,7.89709,Warren&Pearson,NaN,1893,7.89709
11,1894,123.98,1894,57.2634,68.275,3.7,Homer,1894,3.96932,Grebler,1894,NaN,Grebler,1894,6.85048,Warren&Pearson,NaN,1894,6.85048
12,1895,117.455,1895,61.4703,69.58,3.46,Homer,1895,3.60372,Grebler,1895,NaN,Grebler,1895,6.56505,Warren&Pearson,NaN,1895,6.56505
13,1896,100.303,1896,60.0689,70.885,3.6,Homer,1896,3.12206,Grebler,1896,NaN,Grebler,1896,6.66019,Warren&Pearson,NaN,1896,6.66019
14,1897,106.516,1897,62.3849,72.189,3.4,Homer,1897,3.22072,Grebler,1897,NaN,Grebler,1897,6.4699,Warren&Pearson,NaN,1897,6.4699
15,1898,110.184,1898,61.438,73.494,3.35,Homer,1898,3.42963,Grebler,1898,NaN,Grebler,1898,6.66019,Warren&Pearson,NaN,1898,6.66019
16,1899,103.853,1899,64.0446,74.799,3.1,Homer,1899,3.27875,Grebler,1899,NaN,Grebler,1899,6.75534,Warren&Pearson,NaN,1899,6.75534
17,1900,101.574,1900,49.4206,76.094,3.15,Homer,1900,3.7488,Grebler,1900,NaN,Grebler,1900,7.89709,Warren&Pearson,NaN,1900,7.89709
18,1901,87.3261,1901,51.2523,77.584,3.1,Homer,1901,3.14528,Grebler,1901,NaN,Grebler,1901,7.70679,Warren&Pearson,NaN,1901,7.70679
19,1902,100.474,1902,50.5162,79.163,3.18,Homer,1902,3.70818,Grebler,1902,NaN,Grebler,1902,7.89709,Warren&Pearson,NaN,1902,7.89709
20,1903,93.0749,1903,43.5435,80.632,3.3,Homer,1903,3.76621,Grebler,1903,NaN,Grebler,1903,8.65826,Warren&Pearson,NaN,1903,8.65826
21,1904,101.854,1904,47.0856,82.166,3.4,Homer,1904,3.9403,Grebler,1904,NaN,Grebler,1904,8.27768,Warren&Pearson,NaN,1904,8.27768
22,1905,87.2485,1905,47.111,83.822,3.48,Homer,1905,3.45284,Grebler,1905,NaN,Grebler,1905,8.46793,Warren&Pearson,NaN,1905,8.46793
23,1906,103.525,1906,51.7691,85.45,3.43,Homer,1906,4.09698,Grebler,1906,NaN,Grebler,1906,8.46793,Warren&Pearson,NaN,1906,8.46793
24,1907,109.317,1907,49.5447,87.008,3.67,Homer,1907,4.52061,Grebler,1907,NaN,Grebler,1907,8.84851,Warren&Pearson,NaN,1907,8.84851
25,1908,100.819,1908,50.1257,88.71,3.87,Homer,1908,4.07957,Grebler,1908,NaN,Grebler,1908,8.65826,Warren&Pearson,NaN,1908,8.65826
26,1909,95.3804,1909,44.0717,90.49,3.76,Homer,1909,3.98673,Grebler,1909,NaN,Grebler,1909,8.94367,Warren&Pearson,NaN,1909,8.94367
27,1910,93.1106,1910,37.9818,92.407,3.91,Homer,1910,4.3059,Grebler,1910,NaN,Grebler,1910,9.89517,Warren&Pearson,NaN,1910,9.89517
28,1911,97.5433,1911,42.2976,93.863,3.98,Homer,1911,4.20724,Grebler,1911,NaN,Grebler,1911,9.22909,Warren&Pearson,NaN,1911,9.22909
29,1912,102.365,1912,42.2541,95.335,4.01,Homer,1912,4.36973,Grebler,1912,NaN,Grebler,1912,9.134,Warren&Pearson,NaN,1912,9.134
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
834,2016.71,163.128,NaN,NaN,NaN,NaN,NaN,2016.71,184.059,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2016.71,241.428,BLS,NaN,NaN,NaN
835,2016.79,162.997,NaN,NaN,NaN,NaN,NaN,2016.79,184.141,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2016.79,241.729,BLS,NaN,NaN,NaN
836,2016.87,163.448,NaN,NaN,NaN,NaN,NaN,2016.87,184.363,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2016.87,241.353,BLS,NaN,NaN,NaN
837,2016.96,163.552,NaN,NaN,NaN,NaN,NaN,2016.96,184.541,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2016.96,241.432,BLS,NaN,NaN,NaN
838,2017.04,162.829,NaN,NaN,NaN,NaN,NaN,2017.04,184.795,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.04,242.839,BLS,NaN,NaN,NaN
839,2017.12,162.649,NaN,NaN,NaN,NaN,NaN,2017.12,185.172,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.12,243.603,BLS,NaN,NaN,NaN
840,2017.21,163.837,NaN,NaN,NaN,NaN,NaN,2017.21,186.676,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.21,243.801,BLS,NaN,NaN,NaN
841,2017.29,165.109,NaN,NaN,NaN,NaN,NaN,2017.29,188.683,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.29,244.524,BLS,NaN,NaN,NaN
842,2017.37,166.718,NaN,NaN,NaN,NaN,NaN,2017.37,190.685,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.37,244.733,BLS,NaN,NaN,NaN
843,2017.46,168.09,NaN,NaN,NaN,NaN,NaN,2017.46,192.428,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.46,244.955,BLS,NaN,NaN,NaN
844,2017.54,169.309,NaN,NaN,NaN,NaN,NaN,2017.54,193.69,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.54,244.786,BLS,NaN,NaN,NaN
845,2017.62,169.542,NaN,NaN,NaN,NaN,NaN,2017.62,194.538,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.62,245.519,BLS,NaN,NaN,NaN
846,2017.71,169.063,NaN,NaN,NaN,NaN,NaN,2017.71,195.015,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.71,246.819,BLS,NaN,NaN,NaN
847,2017.79,169.401,NaN,NaN,NaN,NaN,NaN,2017.79,195.282,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.79,246.663,BLS,NaN,NaN,NaN
848,2017.87,169.714,NaN,NaN,NaN,NaN,NaN,2017.87,195.647,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.87,246.669,BLS,NaN,NaN,NaN
849,2017.96,170.17,NaN,NaN,NaN,NaN,NaN,2017.96,196.058,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.96,246.524,BLS,NaN,NaN,NaN
850,2018.04,169.496,NaN,NaN,NaN,NaN,NaN,2018.04,196.345,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.04,247.867,BLS,NaN,NaN,NaN
851,2018.12,169.425,NaN,NaN,NaN,NaN,NaN,2018.12,197.152,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.12,248.991,BLS,NaN,NaN,NaN
852,2018.21,170.486,NaN,NaN,NaN,NaN,NaN,2018.21,198.836,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.21,249.554,BLS,NaN,NaN,NaN
853,2018.29,171.564,NaN,NaN,NaN,NaN,NaN,2018.29,200.888,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.29,250.546,BLS,NaN,NaN,NaN
854,2018.37,172.432,NaN,NaN,NaN,NaN,NaN,2018.37,202.745,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.37,251.588,BLS,NaN,NaN,NaN
855,2018.46,173.518,NaN,NaN,NaN,NaN,NaN,2018.46,204.347,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.46,251.989,BLS,NaN,NaN,NaN
856,2018.54,174.292,NaN,NaN,NaN,NaN,NaN,2018.54,205.272,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.54,252.006,BLS,NaN,NaN,NaN
857,2018.62,174.514,NaN,NaN,NaN,NaN,NaN,2018.62,205.647,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.62,252.146,BLS,NaN,NaN,NaN
858,2018.71,174.362,NaN,NaN,NaN,NaN,NaN,2018.71,205.707,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.71,252.439,BLS,NaN,NaN,NaN
859,2018.79,174.056,NaN,NaN,NaN,NaN,NaN,2018.79,205.709,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.79,252.885,BLS,NaN,NaN,NaN
860,2018.87,174.439,NaN,NaN,NaN,NaN,NaN,2018.87,205.471,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.87,252.038,BLS,NaN,NaN,NaN
861,2018.96,174.659,NaN,NaN,NaN,NaN,NaN,2018.96,205.073,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.96,251.233,BLS,NaN,NaN,NaN
862,2019.04,174.016,NaN,NaN,NaN,NaN,NaN,2019.04,204.708,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2019.04,251.712,BLS,NaN,NaN,NaN
863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019.12,252.776,BLS,NaN,NaN,NaN

Когда это может пригодиться? Например, если мы принимаем файл в одном месте программы, а используем в другом. Это может оптимизировать затрачиваемое время, если мы не знаем заранее, когда будем использовать содержимое файла. Ещё один случай:   в файле есть несколько страниц и нам не нужны все эти страницы сразу. Если мы будем читать страницы порознь с помощью read_excel и передавать в этот метод путь к файлу, мы будем каждый раз загружать этот файл в память. Когда данных много, это заполнит вашу оперативную память. В случае с ExcelFile мы прочитаем файл один раз и потом будем только подгружать необходимые страницы.

С ExcelFile можно работать с помощью контекстного менеджера:

In [14]:
# with pd.ExcelFile('file_name.xls') as xls:
#     data['Sheer1'] = pd.read_excel(xls, 'Sheet1', na_values=['NA'])
#     data['Sheet2'] = pd.read_excel(xls, 'Sheet2')

### Чтение по ссылке

In [15]:
data = pd.read_excel('http://www.econ.yale.edu/~shiller/data/Fig3-1.xls', header=None)

Часто приходится работать с таблицами, не имеющими настолько чёткой структуры или содержащих много дополнительной, значимой для нас информации: номер документа, дата его подписания, фамилия сотрудника, чья подпись стоит на документе. (file nakladnaya.xls)

Что нам может понадобиться в этих данных? Во-первых, это названия компаний, имена людей, номер и дата накладной. Во-вторых, табличные данные в центре файла — информация об объектах, которые были куплены.

### Пустые строки
Если мы посмотрим на то, как выглядит файл, то увидим, что первые две строчки — пустые, и при чтении файла их желательно пропустить. Для этого можно передать в функцию read_excel дополнительный параметр — skiprows. В качестве значения параметра укажем количество строк, которые надо пропустить при чтении:

In [22]:
data = pd.read_excel('nakladnaya.xls', header=None, skiprows=2)

Здесь вместо X нужно написать количество строк, которые мы хотим пропустить. Если мы хотим пропустить строки не в начале, а в конце, то нужно использовать параметр skipfooter, он работает точно так же.

In [24]:
data.dropna(how='all', inplace=True)
len(data)

15

In [32]:
# код поможет узнать номер накладной
data.iloc[0,4][2:9]

'5764809'

In [39]:
#same functionality code
# data.iloc[6:8, [1, 2, 6, 9, 11, 12]]
# data.iloc[6:8, :].dropna(axis=1, how='any')
table = data.iloc[6:8, :].dropna(axis=1, how='all')

### Запись в Excel-файл

In [40]:
table.to_excel('table.xls', index=False)

In [41]:
writer = pd.ExcelWriter('test.xlsx')
table.to_excel(writer, index=False, sheet_name='Таблица')
writer.save()

Во-первых, мы все равно использовали метод to_excel(), но вместо пути к будущему файлу передали объект типа ExcelWriter, который создали на первой строке. Во-вторых, мы вызвали метод save() у объекта ExcelWriter. До этого момента сохранение не было завершено, и мы могли сделать еще некоторые действия. Какие? Давайте узнаем.

### Добавим форматирование

Как мы узнали в самом начале, Excel-файлы поддерживают форматирование текста. С помощью pandas мы можем добавлять форматирование в Excel-файлы, используя ExcelWriter. Если мы хотим добавить форматирование, нужно выбрать объект workbook, с помощью которого мы будем добавлять, например, выделение текста жирным. Кроме этого, нужно выбрать нужную страницу:

In [50]:
writer = pd.ExcelWriter('test.xlsx')
table.to_excel(writer, index=False, sheet_name='Таблица')

workbook = writer.book
worksheet = writer.sheets['Таблица']

Теперь давайте выделим цену и сумму жирным, а наименование – красным цветом:

In [51]:
money_fmt = workbook.add_format({'bold':True, 'fg_color':'green'})
name_fmt = workbook.add_format({'color':'red'})

worksheet.set_column('E:F', 20, money_fmt)
worksheet.set_column(1, 1, 20, name_fmt)

writer.save()

Что здесь произошло? 

1. Мы создали два объекта с описанием двух типов форматирования:

    - для оформления цены и стоимости – полужирное начертание; 
    - для оформления наименований товаров – красный цвет текста.  
2. Связали описанные типы форматирования с определёнными ячейками листа "Таблица": 

    - для столбцов E-F выбрали форматирование money_fmt (применяется для оформления цены и стоимости); 
    - для столбца 1, который отвечает за наименование, выбрали форматирование name_fmt. 
Для выбора нужных столбцов при задании параметров форматирования мы использовали два способа. Один из них — с помощью буквенных обозначений. Это стандартный способ обращаться к столбцам в Excel. Второй — с помощью номера столбца.

Важно запомнить, что при работе с Excel при задании диапазона значений значения указываются включительно. Именно поэтому мы выбрали во втором случае применение форматирования от столбца 1 до столбца 1.

Ещё одна вещь, на которую нужно обратить внимание: число 20 среди параметров метода set_column(). Этот параметр означает ширину столбца. Например, если мы передадим число 300, столбец получится очень широким, вы можете убедиться в этом сами.

Какие еще параметры можно попробовать:

- border отвечает за границы столбца и может быть равен True или False; 
- align отвечает за расположение данных внутри ячеек, например, center для настройки выравнивания по центру; 
- fg_color отвечает за цвет фона, например, 'green', хотя можно передать и шестнадцатиричное значение, например, '#D7E4BC'.